"""
This file contains the names of the prompts used in the `judgement/` dir.

"""
ANONYMIZATION_PROMPT = "ANONYMIZE_DOC"
ANONYMIZATION_PAIR_PROMPT = "ANONYMIZE_PAIR_OF_DOCS"
LLM_GEN_CRITIERIA = "GENERATE_CRITERIA"
LETTER_COMPARISON = "LETTER_COMPARISON"
MIXTURE_OF_JUDGES = "mixture_of_judges_base"
ARENA_HARD_ESQUE = "ARENA_HARD_ESQUE"
